# Generated by Django 5.0.6 on 2024-05-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='responsavel',
            new_name='responsavel',
        ),
    ]
