# Generated by Django 5.0.6 on 2024-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_umidadedata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
