# Generated by Django 5.0.6 on 2024-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sensor_unidade_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturadata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
